esphome:
  name: light-train
  friendly_name: light-train
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32c3
  name_add_mac_suffix: true
  project:
    name: "blamejoel.light-train"
    version: "0.1"
  min_version: "2024.11.1"

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret lt_api_key

ota:
  - platform: esphome
    password: !secret lt_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: None

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Light-Train Fallback Hotspot"
    password: !secret lt_ap_password

captive_portal:

script:
  - id: animate
    then:
      - switch.turn_on: motor_relay
      - delay: 1min
      - switch.turn_off: motor_relay
  - id: standby_lights
    then:
      - light.turn_on: lights
      - delay: 30s
      - light.turn_off: lights
  - id: light_show
    then:
      - light.turn_on:
          id: lights
          effect: "Rainbow"
          brightness: 20%
      - delay: 1min
      - light.turn_off: lights

output:
  - platform: gpio
    pin: GPIO4
    id: relay_2
  - platform: gpio
    pin: GPIO5
    id: relay_3
  - platform: gpio
    pin: GPIO6
    id: relay_4

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 300s
    entity_category: "diagnostic"
  - platform: uptime
    type: seconds
    name: "Uptime Sensor"
  - platform: internal_temperature
    name: "Internal Temperature"

binary_sensor:
  # Connected status
  - platform: status
    name: "Train Status"
  # Motor sensor
  - platform: template
    id: relay_on
    name: "Motor Active"
    device_class: moving
    icon: "mdi:motion"
    condition:
      switch.is_on: motor_relay
  # Onboard manual movement
  - platform: gpio
    id: onboard_move
    name: "Manual Override"
    pin:
      number: GPIO20
      mode: INPUT_PULLDOWN
    filters:
      - delayed_on: 10ms
    icon: "mdi:account-arrow-right"
    on_press:
      then:
        - switch.turn_on: motor_relay
    on_release:
      then:
        - switch.turn_off: motor_relay

switch:
  - platform: gpio
    id: motor_relay
    internal: true
    pin: GPIO3
  - platform: template
    id: show_enabled
    name: "Enabled"
    icon: "mdi:refresh-auto"
    optimistic: true

button:
  - platform: template
    id: ha_move
    name: "Remote Control"
    on_press:
      - switch.turn_on: motor_relay
      - delay: 2s
      - switch.turn_off: motor_relay
    icon: "mdi:train"
  - platform: output
    name: "Short Tracks/Horn"
    output: relay_2
    duration: 200ms
    icon: "mdi:fence-electric"
  - platform: output
    name: "Long Tracks"
    output: relay_3
    duration: 200ms
    icon: "mdi:fence"
  - platform: output
    name: "Horn"
    output: relay_4
    duration: 200ms
    icon: "mdi:bugle"
  - platform: template
    name: "Run Train"
    icon: "mdi:play"
    on_press:
      then:
        - script.execute: light_show
        - script.execute: animate
  - platform: template
    name: "Stop Train"
    icon: "mdi:stop"
    on_press:
      then:
        - switch.turn_off: motor_relay
        - light.turn_off: lights
        - script.stop: animate
        - script.stop: light_show
  - platform: template
    name: "Light Show"
    icon: "mdi:string-lights"
    on_press:
      then:
        script.execute: light_show

light:
  - platform: esp32_rmt_led_strip
    id: lights
    rgb_order: GRB
    pin: GPIO21
    num_leds: 290
    rmt_channel: 0
    bit0_high: 0.4us
    bit0_low: 0.85us
    bit1_high: 0.8us
    bit1_low: 0.45us
    reset_low: 55us
    name: "Train Lights"
    effects:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_random_twinkle:
        # twinkle_probability: 50%
      - addressable_fireworks:
        # spark_probability: 50%
        # use_random_color: true
      - addressable_flicker:
    on_turn_on:
      - light.turn_on:
          id: lights
          brightness: 20%
